name: Run tests

on: [push]

jobs:
  tests:
    name: Run tests with spring boot version compatibility check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spring-boot: [ '3.4.13', '3.5.14' ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: db-scheduler-ui-frontend/package.json

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          cache-dependency-path: db-scheduler-ui-frontend/pnpm-lock.yaml

      - name: Install Node.js dependencies
        working-directory: db-scheduler-ui-frontend
        run: pnpm install --frozen-lockfile

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests
        run: mvn -B -Dspring-boot.version=${{ matrix.spring-boot }} clean test --file pom.xml

  tests-boot4:
    name: Run tests with Spring Boot 4
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spring-boot-4: [ '4.0.6' ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: db-scheduler-ui-frontend/package.json

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          cache-dependency-path: db-scheduler-ui-frontend/pnpm-lock.yaml

      - name: Install Node.js dependencies
        working-directory: db-scheduler-ui-frontend
        run: pnpm install --frozen-lockfile

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests
        run: mvn -B -Dspring-boot-4.version=${{ matrix.spring-boot-4 }} -pl db-scheduler-ui-spring-boot-4-starter,example-app-boot4 -am clean test --file pom.xml
